package com.ishanitech.ipalika.utils;

import com.fasterxml.jackson.annotation.JsonValue;

public enum FormInfoUtil {
    BIRTH_CERTIFICATE(1),
    RELATIONSHIP_LIVING(2),
    RELATIONSHIP_DECEASED(3),
    MARRIAGE_CERTIFICATE(4),
    DEATH_CERTIFICATE(5),
    DIVORCE_CERTIFICATE(6),
    DISABLED_CERTIFICATE(7),
    MARRIAGE_VERIFICATION(8),
    ALIVE_CERTIFICATE(9),
    MINOR_CERTIFICATE(10),
    SCHOLARSHIP_CERTIFICATE(11),
    BIRTH_VERIFICATION(12),
    PERMANENT_RESIDENCE(13),
    PIPELINE_CONNECTION(14),
    LAND_MARKING(15),
    GHAR_KAYAM(16),
    POOR_ECONOMY(17),
    ENGLISH_VERIFICATION(18),
    MANJURINAMA_VERIFICATION(19),
    GHAR_PATAL(20),
    ELECTRICITY_CONNECTION(21),
    TWO_NAMES(22),
    BUSINESS_NOT_OPERATING(23),
    LAND_DHANIPURJA(24),
    KOTHA_KHOLNA_KARYA(25),
    BATO_KAYAM(26),
    GUARDIAN_PERSONAL(27),
    GUARDIAN_INSTITUTIONAL(28),
    PERSONAL_DETAILS(29),
    SCHOOL_TRANSFER(30),
    INDUSTRY_TRANSFER(31),
    MOHI_LAGAT(32),
    HOUSE_LAND_TRANSFER(33),
    HOME_ROAD(34),
    MALPOT_BHUMIKAR(35),
    ADVERTISEMENT_TAX(36),
    RECONCILIATION_PAPER(37),
    CHAR_KILLA(38),
    INSTITUTION_REGISTER(39),
    FREE_HEALTHCARE(40),
    SCHOOL_OPERATION(41),
    INTERNAL_RESIDENCE(42),
    COURT_FEE(43),
    BUSINESS_CLOSURE(44),
    ANGIKRIT_CITIZENSHIP(45),
    CITIZENSHIP_AND_COPY(46),
    RESETTLEMENT_REGISTER(47),
    BUSINESS_REGISTER(48),
    QUADRUPED(49),
    DETAILS_DISCLOSURE(50);

    @JsonValue
    private final Integer formInfoId;

    private FormInfoUtil(Integer formInfoId) {
        this.formInfoId = formInfoId;
    }

    public Integer getFormId() {
        return formInfoId;
    }
}
